# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.3.2
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-02-17T10:13:30Z"
  labels:
    app: mlproject-pod
  name: mlproject-pod
spec:
  containers:
  - image: docker.io/mlevytskyi089/ml_project:latest
    imagePullPolicy: Always
    name: mlproject
    ports:
    - containerPort: 80
      hostPort: 8080

