version: '3.8'
services:
  ai-agent:
    build: ./ai-agent
    ports:
      - "5001:5000"
  api:
    build: ./api
    ports:
      - "5002:5000"
  frontend:
    build: ./frontend
    ports:
      - "80:80"
  database:
    build: ./database
    ports:
      - "5432:5432"
