apiVersion: v1
kind: Service
metadata:
  name: iris-service
spec:
  selector:
    app: iris-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000  # You can specify a port in the range 30000-32767
  type: NodePort
